# GAN Project
## Liz Parker, Colin Craighead, and Aren Dalloul

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf
from keras import layers
from keras import models
from keras import utils
import tensorflow.keras.preprocessing.image as img
import scipy.io
from PIL import Image

Using TensorFlow backend.


## Preparing the Dataset

In [3]:
test_mat = scipy.io.loadmat("data/test_data.mat")
train_mat = scipy.io.loadmat("data/train_data.mat")

In [4]:
def unpack_mat(mat, train_or_test):
    df = pd.DataFrame()
    paths = []
    breeds = []
    breed_ids = []
    num_datapoints = len(mat[train_or_test][0][0][0])
    for i in range(num_datapoints):
        path = "data/images/" + mat[train_or_test][0][0][0][i][0][0]
        paths.append(path)
        temp_arr = mat[train_or_test][0][0][1][i][0][0].strip().split('-')
        breed_str = "-".join(temp_arr[1:]).split('/')[0]
        breeds.append(breed_str)
        breed_ids.append(mat[train_or_test][0][0][2][i][0])
    df['breed'] = breeds
    df['breed_id'] = breed_ids
    df['path'] = paths
    return df

In [5]:
train_df = unpack_mat(train_mat, 'train_info')
test_df = unpack_mat(test_mat, 'test_info')
train_df.head()

breed  breed_id                                               path
0  Chihuahua         1  data/images/n02085620-Chihuahua/n02085620_5927...
1  Chihuahua         1  data/images/n02085620-Chihuahua/n02085620_4441...
2  Chihuahua         1  data/images/n02085620-Chihuahua/n02085620_1502...
3  Chihuahua         1  data/images/n02085620-Chihuahua/n02085620_1916...
4  Chihuahua         1  data/images/n02085620-Chihuahua/n02085620_1315...

In [6]:
X_train = np.array([img.img_to_array(img.load_img(path)) for path in train_df['path']])
print(X_train[0])

[[[ 30.  23.   5.]
  [ 30.  23.   5.]
  [ 30.  23.   5.]
  ...
  [ 65.  49.  13.]
  [ 65.  49.  13.]
  [ 65.  49.  13.]]

 [[ 30.  23.   5.]
  [ 30.  23.   5.]
  [ 30.  23.   5.]
  ...
  [ 65.  49.  13.]
  [ 65.  49.  13.]
  [ 65.  49.  13.]]

 [[ 30.  23.   5.]
  [ 30.  23.   5.]
  [ 30.  23.   5.]
  ...
  [ 65.  49.  13.]
  [ 65.  49.  13.]
  [ 65.  49.  13.]]

 ...

 [[110. 121. 113.]
  [112. 123. 115.]
  [115. 128. 119.]
  ...
  [ 93. 115. 103.]
  [ 89. 111.  99.]
  [ 79. 101.  89.]]

 [[115. 127. 125.]
  [116. 128. 126.]
  [118. 130. 126.]
  ...
  [ 84. 105.  96.]
  [ 86. 107.  98.]
  [ 82. 103.  94.]]

 [[116. 130. 130.]
  [117. 132. 129.]
  [118. 133. 130.]
  ...
  [ 85. 106.  97.]
  [ 93. 114. 105.]
  [ 95. 116. 107.]]]


In [7]:
train_df['height'] = [x.shape[0] for x in X_train]
train_df['width'] = [x.shape[1] for x in X_train]